// <auto-generated />
using System;
using FlowerShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowerShop.Migrations
{
    [DbContext(typeof(FlowerShopContext))]
    [Migration("20251203154907_InitialIdentitySchema")]
    partial class InitialIdentitySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlowerShop.Models.Client", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FlowerShop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FlowerShop.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("FlowerShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Wedding",
                            Color = "Red",
                            ImageUrl = "https://images.pexels.com/photos/7666520/pexels-photo-7666520.jpeg",
                            Name = "Classic Rose Bouquet",
                            Price = 68m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Wedding",
                            Color = "Pink",
                            ImageUrl = "https://images.pexels.com/photos/4993265/pexels-photo-4993265.jpeg",
                            Name = "Peony Petal Ensemble",
                            Price = 74m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Birthday",
                            Color = "Mixed",
                            ImageUrl = "https://images.pexels.com/photos/1108650/pexels-photo-1108650.jpeg",
                            Name = "Spring Tulip Medley",
                            Price = 59m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Birthday",
                            Color = "Mixed",
                            ImageUrl = "https://images.pexels.com/photos/70330/pexels-photo-70330.jpeg",
                            Name = "Garden Soirée Bouquet",
                            Price = 62m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Anniversary",
                            Color = "Red",
                            ImageUrl = "https://images.pexels.com/photos/34701055/pexels-photo-34701055.jpeg",
                            Name = "Velvet Rose Arrangement",
                            Price = 72m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Anniversary",
                            Color = "Pink",
                            ImageUrl = "https://images.pexels.com/photos/2067627/pexels-photo-2067627.jpeg",
                            Name = "Ranunculus Romance",
                            Price = 80m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Wedding",
                            Color = "Pink",
                            ImageUrl = "https://images.unsplash.com/photo-1457089328109-e5d9bd499191?auto=format&fit=crop&w=800&q=80",
                            Name = "Blushing Dahlia Dreams",
                            Price = 76m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Birthday",
                            Color = "Yellow",
                            ImageUrl = "https://images.pexels.com/photos/7382844/pexels-photo-7382844.jpeg",
                            Name = "Sunlit Wildflower Basket",
                            Price = 70m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Wedding",
                            Color = "Purple",
                            ImageUrl = "https://images.pexels.com/photos/34749326/pexels-photo-34749326.jpeg",
                            Name = "Orchid Cascade Luxe",
                            Price = 92m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Thank You",
                            Color = "Purple",
                            ImageUrl = "https://images.pexels.com/photos/207518/pexels-photo-207518.jpeg",
                            Name = "Lavender Meadow Mix",
                            Price = 66m
                        },
                        new
                        {
                            Id = 11,
                            Category = "Sympathy",
                            Color = "Blue",
                            ImageUrl = "https://images.pexels.com/photos/14955886/pexels-photo-14955886.jpeg",
                            Name = "Pastel Hydrangea Box",
                            Price = 78m
                        },
                        new
                        {
                            Id = 12,
                            Category = "Thank You",
                            Color = "Purple",
                            ImageUrl = "https://images.pexels.com/photos/1381679/pexels-photo-1381679.jpeg",
                            Name = "Violet Garden Posy",
                            Price = 63m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Birthday",
                            Color = "Yellow",
                            ImageUrl = "https://images.pexels.com/photos/1405699/pexels-photo-1405699.jpeg",
                            Name = "Golden Hour Blossoms",
                            Price = 75m
                        },
                        new
                        {
                            Id = 14,
                            Category = "Thank You",
                            Color = "Pink",
                            ImageUrl = "https://images.pexels.com/photos/20865664/pexels-photo-20865664.jpeg",
                            Name = "Rosewater Gift Crate",
                            Price = 69m
                        },
                        new
                        {
                            Id = 15,
                            Category = "Wedding",
                            Color = "Pink",
                            ImageUrl = "https://images.pexels.com/photos/2123755/pexels-photo-2123755.jpeg",
                            Name = "Cherry Blossom Spray",
                            Price = 88m
                        },
                        new
                        {
                            Id = 16,
                            Category = "Sympathy",
                            Color = "White",
                            ImageUrl = "https://images.pexels.com/photos/6044630/pexels-photo-6044630.jpeg",
                            Name = "Magnolia Signature Arrangement",
                            Price = 95m
                        },
                        new
                        {
                            Id = 17,
                            Category = "Anniversary",
                            Color = "Green",
                            ImageUrl = "https://images.pexels.com/photos/5501101/pexels-photo-5501101.jpeg",
                            Name = "Botanical Garden Luxe",
                            Price = 109m
                        },
                        new
                        {
                            Id = 18,
                            Category = "Wedding",
                            Color = "Mixed",
                            ImageUrl = "https://images.pexels.com/photos/16961730/pexels-photo-16961730.jpeg",
                            Name = "Eucalyptus Rose Harmony",
                            Price = 82m
                        },
                        new
                        {
                            Id = 19,
                            Category = "Sympathy",
                            Color = "White",
                            ImageUrl = "https://images.pexels.com/photos/10679724/pexels-photo-10679724.jpeg",
                            Name = "Starlit Lily Collection",
                            Price = 90m
                        },
                        new
                        {
                            Id = 20,
                            Category = "Anniversary",
                            Color = "Red",
                            ImageUrl = "https://images.pexels.com/photos/10533594/pexels-photo-10533594.jpeg",
                            Name = "Crimson Peony Statement",
                            Price = 84m
                        },
                        new
                        {
                            Id = 21,
                            Category = "Sympathy",
                            Color = "White",
                            ImageUrl = "https://images.pexels.com/photos/17858332/pexels-photo-17858332.jpeg",
                            Name = "White Garden Symphony",
                            Price = 77m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FlowerShop.Models.Order", b =>
                {
                    b.HasOne("FlowerShop.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FlowerShop.Models.Client", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FlowerShop.Models.Client", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowerShop.Models.Client", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FlowerShop.Models.Client", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
